spring.application.name=demo-park-api

# LOCALE
spring.web.locale-resolver=fixed
spring.web.locale=pt_BR

# DB Connection
# postgresql://postgres:mlqvo28nscy8kqcm@177.7.47.28:5434/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://177.7.47.28:5434/postgres?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=mlqvo28nscy8kqcm

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=update

# Springdoc OpenApi 3.1 & Swagger 3
springdoc.swagger-ui.path=/docs-park.html
springdoc.api-docs.path=/docs-park
springdoc.packagesToScan=com.mballem.demoparkapi.web.controller

# Custom
server.port=8081
spring.jackson.mapper.sort-properties-alphabetically=false